# RENAME FILE TO 'config.yml'
bot:
  token: MTI0MTUyNjA1ODM1MjkwMjIyNw.Gpaw24.4WUKmKXoGKfRruyNymhHHtE_sTusDoHQaN52jE
  owner_ids:
    - 1241523150462779427
    - 1241526058352902227
  prefix: $
  default_bet: 100
  bonus_multiplier: 5 # bonus = default_bet * multiplier
  bonus_cooldown: 12 # Bonus every x hours
